<?php
/**
 * Скелет сайта.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
?>
<!DOCTYPE html>
<html>
	<head>
		<?= $this->render($variables, 'layout/head') ?>
	</head>
	<body>
		<div class="main">
			<?= $this->render($variables, 'layout/header/index') ?>
			<?= $this->render($variables, 'layout/content/index') ?>
			<div class="compensator"></div>
		
		<?= $this->render($variables, 'layout/footer/index') ?>
		</div>
	</body>
</html>
