<?php
/**
 * Шапка сайта
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
?>
<!--
<div class="row-fluid for-main-header">
	<div class="span12 prel">
		<div class="cover-one"></div>
		<div class="container">
			<div class="row-fluid umi-header">
				<div class="span12">
					<div class="head_wr">
						<div class="head_search">
							<?= $this->render($this->macros('search', 'insert_form'), 'search/insert_form') ?>
							
						</div>
						<div class="head_logo_wr">
							<?= $this->render($variables, 'layout/header/text') ?>
						</div>
						<div class="head_img_wr">
							<?= $this->render($variables, 'layout/header/image') ?>
						</div>
					</div>
				</div>
			</div>
			<div class="head_search_second mainer">
				<?= $this->render($this->macros('search', 'insert_form'), 'search/insert_form') ?>
			</div>
		</div>
	</div>
</div>
<div class="row-fluid for-menu">
	<div class="span12 prel">
		<div class="cover-two"></div>
		<div class="container">
			<div class="row-fluid umi-menu">
				<div class="span12">
					<div class="navbar">
						<div class="navbar-inner">
							<div class="container">
								<?= $this->render($this->getMenu(), 'content/menu') ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
-->

	<header class="main__head">
      <div class="fix-menu">
  <nav class="navbar fix-color">
     <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
            <a class="navbar-brand fix-brand" href="#">
               <img alt="Brand" src="<?= $this->macros('umiTemplates', 'getResourceDirectory') ?>images/logo_a25_2.png">
            </a>
        </div>
  
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right fix-nav">
        <li><a href="#">Главная</a></li>
        <li><a href="#">О нас</a></li>
        <li><a href="#">Новости</a></li>
        <li><a href="#">Прочее</a></li>
        <li><a href="#">Контакты</a></li>
      </ul>
	  
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div> <!-- class="fix-menu" -->
			</header>
