<?php
/**
 * Подвал сайта.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemolancerPhpExtension $this
 * @var array $variables
 */
?>
<footer class="main__footer">
      <div class="row">
  <div class="col-md-6">
     <div class="footer-text fix-magin-left">
           <h1>Контакты</h1>
           <p>Санкт-Петербург 
		      Новорощинская ул., д.4, оф. 1415-1
              БЦ "Собрание",
              ст. метро Электросила
              +7 (812) 603-48-25
           </p>
     </div>
  </div>
  
  <div class="col-md-6">
     <div class="footer-text fix-magin-right">
            <h1>О нас</h1>
           <p>Сотрудничать с А25 – наглядно, 
		   функционально, прозрачно. 
		   Бюджет проекта на продвижение 
		   и развитие сайта базируется на 
		   количестве трудочасов на 
		   каждую задачу. Политика 
		   ценообразования А25 позволяет 
		   формировать гибкий и открытый 
		   план работ, который согласуется 
		   с клиентом. Проект легко 
		   оптимизируется и делится 
		   на понятные этапы работ.
            </p>
      </div>
  </div>
</div>
    
</footer>
</div><!-- class="main" -->

<script charset="utf-8" src="js/jquery-3.4.1.min.js" type="text/javascript"></script>
<script charset="utf-8" src="js/bootstrap.min.js" type="text/javascript"></script>
<script charset="utf-8" src="js/owl.carousel.js" type="text/javascript"></script>
<script charset="utf-8" src="slick/slick.js" type="text/javascript"></script>
<script charset="utf-8" src="js/main.js" type="text/javascript"></script>


